# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5497dc10ca8f6cdd9c65782dd061b637456ac16eec5af9139f13e7d22694ee83e112bb00cb2b9409e266544f78283ea671566230690409f71da89563d9228f47

test:
  secret_key_base: b76122c04ae7fa1a1898e232161971b597f3dd07b17144c3984cb32f064af753567659446fc9b455ef978c1be911e8de4236ca5e05acdb3a0e9be4a0114cacbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
